[build]
  functions = "functions" 

[dev]
  port = 7777
  staticServerPort = 4444
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/images/*"
  to = "/.netlify/functions/images/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
